//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssetTrackingEntities : DbContext
    {
        public AssetTrackingEntities()
            : base("name=AssetTrackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_AT_DVC> TBL_AT_DVC { get; set; }
        public virtual DbSet<TBL_AT_DVC_CAPBLTY> TBL_AT_DVC_CAPBLTY { get; set; }
        public virtual DbSet<TBL_AT_DVC_TYP> TBL_AT_DVC_TYP { get; set; }
        public virtual DbSet<TBL_AT_DVC_TYP_CAPBLTY> TBL_AT_DVC_TYP_CAPBLTY { get; set; }
        public virtual DbSet<TBL_AT_GPS_PING> TBL_AT_GPS_PING { get; set; }
        public virtual DbSet<TBL_AT_MESSAGE_TYPE> TBL_AT_MESSAGE_TYPE { get; set; }
        public virtual DbSet<TBL_AT_DRCTN> TBL_AT_DRCTN { get; set; }
        public virtual DbSet<TBL_AT_EVNT> TBL_AT_EVNT { get; set; }
        public virtual DbSet<TBL_AT_EVNT_DVC> TBL_AT_EVNT_DVC { get; set; }
        public virtual DbSet<TBL_AT_EVNT_STATE> TBL_AT_EVNT_STATE { get; set; }
        public virtual DbSet<TBL_AT_EVNT_STATE_TYP> TBL_AT_EVNT_STATE_TYP { get; set; }
        public virtual DbSet<TBL_AT_EVNT_TYP> TBL_AT_EVNT_TYP { get; set; }
        public virtual DbSet<TBL_AT_GEOFENCE> TBL_AT_GEOFENCE { get; set; }
        public virtual DbSet<TBL_AT_GEOFENCE_COOR> TBL_AT_GEOFENCE_COOR { get; set; }
        public virtual DbSet<TBL_AT_GEOFENCE_PROP_TYP> TBL_AT_GEOFENCE_PROP_TYP { get; set; }
        public virtual DbSet<TBL_AT_GEOFENCE_PROPERTY> TBL_AT_GEOFENCE_PROPERTY { get; set; }
        public virtual DbSet<TBL_AT_GPS_PING_DATA> TBL_AT_GPS_PING_DATA { get; set; }
        public virtual DbSet<TBL_AT_LOCTN> TBL_AT_LOCTN { get; set; }
        public virtual DbSet<TBL_AT_PERMISSIONS> TBL_AT_PERMISSIONS { get; set; }
        public virtual DbSet<TBL_AT_ROLES> TBL_AT_ROLES { get; set; }
        public virtual DbSet<TBL_AT_STAT> TBL_AT_STAT { get; set; }
        public virtual DbSet<TBL_AT_USERS> TBL_AT_USERS { get; set; }
        public virtual DbSet<TBL_AT_DRCTN1> TBL_AT_DRCTN1 { get; set; }
        public virtual DbSet<TBL_AT_EVNT1> TBL_AT_EVNT1 { get; set; }
        public virtual DbSet<TBL_AT_EVNT_DVC1> TBL_AT_EVNT_DVC1 { get; set; }
        public virtual DbSet<TBL_AT_EVNT_STATE1> TBL_AT_EVNT_STATE1 { get; set; }
        public virtual DbSet<TBL_AT_EVNT_STATE_TYP1> TBL_AT_EVNT_STATE_TYP1 { get; set; }
        public virtual DbSet<TBL_AT_EVNT_TYP1> TBL_AT_EVNT_TYP1 { get; set; }
        public virtual DbSet<TBL_AT_GEOFENCE1> TBL_AT_GEOFENCE1 { get; set; }
        public virtual DbSet<TBL_AT_GEOFENCE_COOR1> TBL_AT_GEOFENCE_COOR1 { get; set; }
        public virtual DbSet<TBL_AT_GEOFENCE_PROP_TYP1> TBL_AT_GEOFENCE_PROP_TYP1 { get; set; }
        public virtual DbSet<TBL_AT_GEOFENCE_PROPERTY1> TBL_AT_GEOFENCE_PROPERTY1 { get; set; }
        public virtual DbSet<TBL_AT_GPS_PING_DATA1> TBL_AT_GPS_PING_DATA1 { get; set; }
        public virtual DbSet<TBL_AT_LOCTN1> TBL_AT_LOCTN1 { get; set; }
        public virtual DbSet<TBL_AT_STAT1> TBL_AT_STAT1 { get; set; }
        public virtual DbSet<TBL_AT_MESSAGE_DATA> TBL_AT_MESSAGE_DATA { get; set; }
        public virtual DbSet<v_GPS_Ping> v_GPS_Ping { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
