//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AT_ROLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_AT_ROLES()
        {
            this.TBL_AT_ROLES1 = new HashSet<TBL_AT_ROLES>();
        }
    
        public int Role_Id { get; set; }
        public string RoleDescription { get; set; }
        public bool IsSysAdmin { get; set; }
        public string RoleName { get; set; }
        public int SuperRoleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_AT_ROLES> TBL_AT_ROLES1 { get; set; }
        public virtual TBL_AT_ROLES TBL_AT_ROLES2 { get; set; }
    }
}
