//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AT_DVC_TYP_CAPBLTY
    {
        public int DVC_TYP_ID { get; set; }
        public int IID { get; set; }
        public int DVC_CAPBLTY_ID { get; set; }
        public string ADDED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
    
        public virtual TBL_AT_DVC_CAPBLTY TBL_AT_DVC_CAPBLTY { get; set; }
        public virtual TBL_AT_DVC_TYP TBL_AT_DVC_TYP { get; set; }
    }
}
