//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AT_GEOFENCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_AT_GEOFENCE()
        {
            this.TBL_AT_GEOFENCE_PROPERTY = new HashSet<TBL_AT_GEOFENCE_PROPERTY>();
            this.TBL_AT_GEOFENCE_COOR = new HashSet<TBL_AT_GEOFENCE_COOR>();
        }
    
        public int IID { get; set; }
        public string GEOFENCE_DESC { get; set; }
        public string GEOFENCE_SHAPE { get; set; }
        public Nullable<int> GEOFENCE_TYP { get; set; }
        public Nullable<int> GEOFENCE_ZNG { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public string ADDED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
    
        public virtual TBL_AT_LOCTN TBL_AT_LOCTN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_AT_GEOFENCE_PROPERTY> TBL_AT_GEOFENCE_PROPERTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_AT_GEOFENCE_COOR> TBL_AT_GEOFENCE_COOR { get; set; }
    }
}
