//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AT_GPS_PING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_AT_GPS_PING()
        {
            this.TBL_AT_GPS_PING_DATA1 = new HashSet<TBL_AT_GPS_PING_DATA1>();
        }
    
        public int IID { get; set; }
        public string GPS_PING_TM { get; set; }
        public string RSSI { get; set; }
        public string SNR { get; set; }
        public string DATA { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
        public string DVC_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_AT_GPS_PING_DATA1> TBL_AT_GPS_PING_DATA1 { get; set; }
    }
}
