//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AT_EVNT1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_AT_EVNT1()
        {
            this.TBL_AT_EVNT_STATE1 = new HashSet<TBL_AT_EVNT_STATE1>();
            this.TBL_AT_EVNT_DVC1 = new HashSet<TBL_AT_EVNT_DVC1>();
        }
    
        public int IID { get; set; }
        public string EVNT_NM { get; set; }
        public string RFRNC_NBR { get; set; }
        public Nullable<System.DateTime> EVNT_STRT_TM { get; set; }
        public Nullable<System.DateTime> EVNT_END_TM { get; set; }
        public Nullable<int> EVNT_TYP_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string ADDED_BY { get; set; }
        public string LAST_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_AT_EVNT_STATE1> TBL_AT_EVNT_STATE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_AT_EVNT_DVC1> TBL_AT_EVNT_DVC1 { get; set; }
        public virtual TBL_AT_EVNT_TYP1 TBL_AT_EVNT_TYP1 { get; set; }
    }
}
