//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AT_DVC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_AT_DVC()
        {
            this.TBL_AT_GPS_PING_DATA = new HashSet<TBL_AT_GPS_PING_DATA>();
            this.TBL_AT_EVNT_DVC = new HashSet<TBL_AT_EVNT_DVC>();
            this.TBL_AT_EVNT_DVC1 = new HashSet<TBL_AT_EVNT_DVC1>();
        }
    
        public int IID { get; set; }
        public string DVC_NM { get; set; }
        public string DVC_CD { get; set; }
        public Nullable<int> DVC_TYP_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
        public string ADDED_BY { get; set; }
    
        public virtual TBL_AT_DVC_TYP TBL_AT_DVC_TYP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_AT_GPS_PING_DATA> TBL_AT_GPS_PING_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_AT_EVNT_DVC> TBL_AT_EVNT_DVC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_AT_EVNT_DVC1> TBL_AT_EVNT_DVC1 { get; set; }
    }
}
