//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AT_LOCTN1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_AT_LOCTN1()
        {
            this.TBL_AT_GEOFENCE1 = new HashSet<TBL_AT_GEOFENCE1>();
        }
    
        public string LOCTN_CD { get; set; }
        public Nullable<int> LOCTN_TYP { get; set; }
        public string COMPANY { get; set; }
        public string LOCTN_NM { get; set; }
        public string LOCTN_NM_2 { get; set; }
        public string LOCTN_ADDR { get; set; }
        public string LOCTN_ADDR_2 { get; set; }
        public string LOCTN_CTY { get; set; }
        public string LOCTN_STATE { get; set; }
        public string LOCTN_PSTL_CODE { get; set; }
        public string LOCTN_CNTRY { get; set; }
        public string LOCTN_ZN { get; set; }
        public string EMAIL { get; set; }
        public string CNTCT { get; set; }
        public int IID { get; set; }
        public string ADDED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_AT_GEOFENCE1> TBL_AT_GEOFENCE1 { get; set; }
    }
}
