//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AT_MESSAGE_DATA
    {
        public int IID { get; set; }
        public Nullable<int> MESSAGE_ID { get; set; }
        public string VALUE { get; set; }
        public string VALUE_TYPE { get; set; }
        public Nullable<int> STARTHEX { get; set; }
        public Nullable<int> STARTBIT { get; set; }
        public Nullable<int> ENDHEX { get; set; }
        public Nullable<int> ENDBIT { get; set; }
    }
}
