//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AT_GPS_PING_DATA1
    {
        public long IID { get; set; }
        public string DVC_ID { get; set; }
        public Nullable<System.DateTime> GPS_PING_DT { get; set; }
        public string GPS_TYP { get; set; }
        public string GPS_STAT { get; set; }
        public Nullable<double> GPS_LAT { get; set; }
        public Nullable<double> GPS_LONG { get; set; }
        public Nullable<decimal> GPS_TEMP { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> GPS_SGNL_TM { get; set; }
        public string GPS_RSSI { get; set; }
        public string GPS_SNR { get; set; }
        public string CMNT { get; set; }
        public string ORNTN { get; set; }
        public string BLCK_TYP { get; set; }
        public int GPS_PING_ID { get; set; }
        public string ADDED_BY { get; set; }
        public string LAST_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
    
        public virtual TBL_AT_GPS_PING TBL_AT_GPS_PING { get; set; }
    }
}
