//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GPS_Ping
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string DocumentID { get; set; }
        public string battery { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Temperature { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string SignalTime { get; set; }
        public string RSSI { get; set; }
        public string SNR { get; set; }
        public string AddedBy { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public int IID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string DeviceName { get; set; }
    }
}
