//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class pingdataview
    {
        public long id { get; set; }
        public string DeviceID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<decimal> Temp { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<int> SignalTime { get; set; }
        public string RSSI { get; set; }
        public string SNR { get; set; }
        public string comment { get; set; }
        public string Orentation { get; set; }
        public string Block_Type { get; set; }
    }
}
