//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AT_GPSPings
    {
        public long IID { get; set; }
        public string DeviceID { get; set; }
        public string Time { get; set; }
        public string Data { get; set; }
        public string RSSI { get; set; }
        public string SNR { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
    }
}
